flask_app/apps/scrapy/models.py
from datetime import datetime
from apps.app import db


class UserKeyword(db.Model):
    __tablename__ = 'user_keywords'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    is_scraped = db.Column(db.Boolean, default=False)
    keyword = db.Column(db.String(255))
    year1 = db.Column(db.String(4))
    year2 = db.Column(db.String(4)) 
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    

flask_app/apps/scrapy/forms.py
from flask_wtf.form import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Regexp

class SerchWordForm(FlaskForm):
    keyword = StringField(
        "検索ワード",
        validators=[
            DataRequired(message="無効な文字が含まれています。英語での入力をお願いします。"), 
            Regexp("^[A-Za-z0-9!@#$%^&*()_+{}:\"<>?,./;'\[\]\\\-]*$")
            ],
        )
    
    year1 = IntegerField(
        "検索開始年",
        validators=[
            DataRequired(message="検索開始年が空です。")
        ]
    )

    year2 = IntegerField(
        "検索終了年",
        validators=[
            DataRequired(message="検索終了年が空です。")
        ]
    )
        
    submit = SubmitField('検索')
    
class ScrapyForm(FlaskForm):
    submit = SubmitField('再検索')
    
class DeleteForm(FlaskForm):
    submit = SubmitField('削除')

flask_app/apps/scrapy/__init__.py
import flask_app.apps.scrapy.models

flask_app/apps/scrapy/views.py
from apps.app import db
from apps.crud.models import User
from flask_app.apps.scrapy.models import UserKeyword
from flask import Blueprint, current_app, render_template, redirect, url_for, flash
from apps.scrapy.forms import SerchWordForm, DeleteForm
from sqlalchemy.exc import SQLAlchemyError
import spacy
from collections import Counter
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
import seaborn as sns
from flask_login import current_user, login_required
import boto3
import requests
from apps import setting
from dotenv import load_dotenv
from os.path import join, dirname


load_dotenv(verbose=True, override=True)

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

sc = Blueprint("scrapy", __name__, template_folder="templates")


@sc.route("/")
def index():
    if current_user.is_authenticated:
    #ログインユーザーが入力したキーワードの一覧取得
        user_keywords = db.session.query(User, UserKeyword).join(UserKeyword).filter(User.id == current_user.id).all()
        

        s3 = boto3.client('s3', aws_access_key_id=setting.AWS_ACCESS_KEY_ID, aws_secret_access_key= setting.AWS_SECRET_ACCESS_KEY)
        bucket_name = 'mytextbukcet'

        url_list = []
        # 各オブジェクトのURLを生成して表示
        for user_keyword in user_keywords:
            keyword = user_keyword.UserKeyword.keyword
            year1 = user_keyword.UserKeyword.year1
            year2 = user_keyword.UserKeyword.year2
            object_url = f'https://{bucket_name}.s3.amazonaws.com/{keyword}_{year1}_{year2}.jpg'
            url_list.append(object_url)
        
        delete_form = DeleteForm()
    
    else:
        flash('ログインが必要です')
        return render_template("auth/index.html")
    return render_template("scrapy/index_book3.html",user_keywords=user_keywords, delete_form=delete_form,url_list=url_list)



@sc.route("/upload_word", methods=["GET", "POST"])
@login_required
def upload_word():
    form = SerchWordForm()
    if form.validate_on_submit():
        keyword = form.keyword.data
        year1 = form.year1.data
        year2 = form.year2.data
        user_keyword = UserKeyword(user_id=current_user.id, keyword = keyword, year1 = year1, year2 = year2) 
        try:
            if int(year1) <= int(year2):
                db.session.add(user_keyword)
                db.session.commit()
                
                return redirect(url_for('scrapy.scrapy'))
        
        except SQLAlchemyError as e:
            flash("検索期間を正しく入力してください。","error")
            db.session.rollback()
            current_app.logger.error(e)
    return render_template("scrapy/search.html", form=form)


def get_paper_abstract(keyword, year1, year2):
    api_key = setting.CORE_API_KEY
    url = f"https://api.core.ac.uk/v3/search/works/?api_key={api_key}" 
    
    query = f"{keyword} AND yearPublished>={year1} AND yearPublished<={year2}"

    # APIを呼び出し、論文タイトルを取得
    params = {
        "apiKey": api_key,
        "q": query,
        "limit": 100,
        "scroll": True
    }

    title_list = []
    abstract_list = []
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        for key in data['results']:
            title_list.append(key['title']) # titleのみ参照
        for key in data['results']:
            abstract_list.append(key['abstract']) # titleのみ参照s
    
    return title_list #, abstract_list


def text_mining(title_list, keyword, year1, year2):
    
    titles = []
    for title in title_list:
        titles.append(title)
    
    titles = ','.join(titles)
    
    nlp = spacy.load("en_core_web_sm")
    
    # テキストを解析
    doc = nlp(titles)

    # 単語を抽出してリストに格納
    words = [token.text.lower() for token in doc if not token.is_stop and not token.is_punct and not token.is_space]

    # 単語の出現頻度を計算
    word_freq = Counter(words)

    # グラフ化
    top_words = 20  # グラフに表示するトップ単語の数を指定

    # 出現頻度が高い単語を取得
    most_common_words = word_freq.most_common(top_words)
    
    fp = matplotlib.font_manager.FontProperties(fname = r'C:\WINDOWS\Fonts\msgothic.ttc', size=12 )

    # グラフの作成
    plt.figure(figsize=(10, 6))
    sns.barplot(x=[word[1] for word in most_common_words], y=[word[0] for word in most_common_words], palette="viridis")
    plt.xlabel('出現頻度', fontproperties=fp)
    plt.ylabel('単語', fontproperties=fp)
    plt.title(f'検索ワード {keyword} / 検索期間 {year1}-{year2} ', fontproperties=fp)
    plt.xticks(rotation=45)

    # グラフをファイル形式で保存
    plt.savefig(f'{keyword}_{year1}_{year2}.jpg', format='jpg')
    
    
    # AWS S3へのアップロード
    s3 = boto3.client('s3', aws_access_key_id=setting.AWS_ACCESS_KEY_ID, aws_secret_access_key= setting.AWS_SECRET_ACCESS_KEY)
    bucket_name = 'mytextbukcet'
    metadata = {
        'keyword': keyword,
        'year1': year1,
        'year2': year2
    }
    s3.upload_file(f'{keyword}_{year1}_{year2}.jpg', bucket_name, f'{keyword}_{year1}_{year2}.jpg', ExtraArgs={'Metadata': metadata})
    
    # 画像のURLを生成
    s3_url = f'https://{bucket_name}.s3.amazonaws.com/{keyword}_{year1}_{year2}.jpg'
    
    return s3_url



@sc.route("/scrapy/scrapy", methods=['POST','GET'])
@login_required
def scrapy():
    #直近で入力したkeywordレコードを取得
    keyword = (
        db.session.query(UserKeyword).order_by(UserKeyword.created_at.desc()).first()  #一旦除外.filter(UserKeyword.id == keyword_id)
    )
    
    if keyword.keyword is None:
        flash("失敗です")
        return redirect(url_for('scrapy.index'))
    
    title_list = get_paper_abstract(keyword.keyword, keyword.year1, keyword.year2)

    try:
        #save_paper(title_list, keyword)
        s3_url = text_mining(title_list, keyword.keyword, keyword.year1, keyword.year2)
    
    except SQLAlchemyError as e:
        flash("エラー発生")
        
        db.session.rollback()
        
        current_app.logger.error(e)
        return redirect(url_for('scrapy.index'))
    
    return redirect(url_for("scrapy.index"))



@sc.route("/delete/<string:keyword_id>", methods=['POST'])
@login_required
def delete_object(keyword_id):
    
    s3 = boto3.client('s3', aws_access_key_id=setting.AWS_ACCESS_KEY_ID, aws_secret_access_key= setting.AWS_SECRET_ACCESS_KEY)
    bucket_name = 'mytextbukcet'
    
    try:
        user_keyword = (db.session.query(UserKeyword).filter(UserKeyword.id == keyword_id).first())
        # 削除するオブジェクトのURLを作製
        keyword = user_keyword.keyword
        year1 = user_keyword.year1
        year2 = user_keyword.year2
        object_url = f'https://{bucket_name}.s3.amazonaws.com/{keyword}_{year1}_{year2}.jpg'
        s3.delete_object(Bucket=bucket_name, Key=object_url)
        #db.session.query(UserScrapy).filter(UserScrapy.user_keyword_id == keyword_id).delete()
        db.session.query(UserKeyword).filter(UserKeyword.id == keyword_id).delete()
        
        db.session.commit()
    except SQLAlchemyError as e:
        flash("keyword削除処理でエラーが発生しました")
        
        current_app.logger.error(e)
        db.session.rollback()
    
    return redirect(url_for("scrapy.index"))

flask_app/apps/scrapy/templates/scrapy/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>detector</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">　
        <div class="container">
            <a class="navbar-brand " href="{{ url_for('scrapy.index') }}">detector</a>

            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>
</body>

</html>

flask_app/apps/scrapy/templates/scrapy/base_1.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="google_scholarから取得した論文の年度や引用件数での並べ替えや、引用件数の平均値・中央値を視覚的に把握できるようにしました">
        <meta name="viewport" content="width=device-width">
        <title>論文検索</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        
    </head>

    <body>
        <nav class="navbar navbar-expanding-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand " href="{{ url_for('scrapy.index') }}">論文検索</a>
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">{{ current_user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}" >ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <section class="container">
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

flask_app/apps/scrapy/templates/scrapy/index_book.html
{% extends "scrapy/base.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li class="flash">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('scrapy.upload_word') }}" class="btn btn-primary">画像新規登録</a>
</div>
<!-- 画像一覧を表示する -->
{% for user_keyword in user_keywords %}
<div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
        <div class="dt-image-username">{{ user_keyword.UserKeyword.keyword }}</div>
        <!-- 物体検知フォームを追加する -->
        <div class="d-flex flex-row-reverse">
            <!-- 削除ボタンのフォームを追加する -->
            <div class="p-2">
                <form action="{{ url_for('scrapy.delete_object', keyword_id=user_keyword.UserKeyword.id) }}" method="POST">
                    {{ delete_form.csrf_token }}
                    {% if current_user.id == user_keyword.User.id %}
                    {{ delete_form.submit(class="btn btn-danger") }}
                    {% else %}
                    {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
                    {% endif %}
                </form>
            </div>
        </div>
    </header>
    <section>
        {% for url in url_list %}
        <div>
        <img src= "{{ url }}">
        </div>
        {% endfor %}
    </section>
</div>
{% endfor %}
{% endblock %}

flask_app/apps/scrapy/templates/scrapy/index_book2.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="google_scholarから取得した論文タイトルに含まれる単語の数を視覚的に把握できるようにしました">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>論文検索</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('scrapy.index') }}">論文検索</a>
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <section class="container my-4">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-info">
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endwith %}

        <div class="row">
            <div class="col-md-10 text-end">
                <a href="{{ url_for('scrapy.upload_word') }}" class="btn btn-primary">画像新規登録</a>
            </div>
        </div>

        <div class="row">
            <div class="card col-md-7 my-3">
                <div class="card-body">
                    {% for user_keyword in user_keywords %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="dt-image-username">{{ user_keyword.UserKeyword.keyword }}</div>
                        <form action="{{ url_for('scrapy.delete_object', keyword_id=user_keyword.UserKeyword.id) }}" method="POST">
                            {{ delete_form.csrf_token }}
                            {% if current_user.id == user_keyword.User.id %}
                            <button type="submit" class="btn btn-danger">削除</button>
                            {% else %}
                            <button type="submit" class="btn btn-danger" disabled>削除</button>
                            {% endif %}
                        </form>
                    </div>
                    {% endfor %}
                </div>
                <div class="card-body">
                    {% for url in url_list %}
                    <section>
                        <img src="{{ url }}" alt="アップロード画像" class="img-fluid" />
                    </section>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
</body>
</html>

flask_app/apps/scrapy/templates/scrapy/index_book3.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>論文検索</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand " href="{{ url_for('scrapy.index') }}">論文検索</a>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        <!-- flashエラーを表示する -->
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="flash">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

        <!-- 画像アップロード画面へのリンクを追加する -->
        <div class="col-md-10 text-right dt-image-register-btn">
            <a href="{{ url_for('scrapy.upload_word') }}" class="btn btn-primary">論文検索</a>
        </div>
        <!-- 画像一覧を表示する -->
        {% for user_keyword in user_keywords %}
        <div class="card col-md-7 dt-image-content">
            <header class="d-flex justify-content-between">
                <div class="dt-image-username">{{ user_keyword.User.username }}</div>
                <!-- 物体検知フォームを追加する -->
                <div class="d-flex flex-row-reverse">
                    <!-- 削除ボタンのフォームを追加する -->
                    <div class="p-2">
                        <form action="{{ url_for('scrapy.delete_object', keyword_id=user_keyword.UserKeyword.id) }}" method="POST">
                            {{ delete_form.csrf_token }}
                            {% if current_user.id == user_keyword.User.id %}
                            {{ delete_form.submit(class="btn btn-danger") }}
                            {% else %}
                            {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </header>
            <section>
                {% for url in url_list %}
                    {% if user_keyword.UserKeyword.keyword in url and user_keyword.UserKeyword.year1 in url and user_keyword.UserKeyword.year2 in url %}
                    <img src="{{ url }}" alt="アップロード画像" />
                    {% endif %}
                {% endfor %}
            </section>
            <footer>
                {{ user_keyword.UserKeyword.keyword }}
            </footer>
        </div>
        {% endfor %}
    </section>
</body>
</html>

flask_app/apps/scrapy/templates/scrapy/search.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="google_scholarから取得した論文の年度や引用件数での並べ替えや、引用件数の平均値・中央値を視覚的に把握できるようにしました">
        <meta name="viewport" content="width=device-width">
        <title>論文検索</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand " href="{{ url_for('scrapy.index') }}">論文検索</a>
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">{{ current_user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}" >ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <section class="container">
            <ul>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in get_flashed_messages() %}
                        <li class="flash">{{ message }}</li>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </ul>
            <div>
                <h4>論文新規検索</h4>
                <p>検索キーワードは英語での入力お願いします</p>
                <form
                    action="{{ url_for('scrapy.upload_word')}}" 
                    method="post"
                >
                    {{ form.csrf_token }}
                    <div>
                        <label>
                            <span>{{ form.keyword(class="form-control-file", placeholder="検索キーワード") }}</span>
                        </label>
                        <br>
                        <br>
                        <label>
                            <span>{{ form.year1(class="form-control-file", placeholder="検索開始年") }}</span>
                        </label>
                        <span style="margin: 0 5px;">～</span> <!-- ダッシュを挿入 -->
                        <label>
                            <span>{{ form.year2(class="form-control-file", placeholder="検索終了年") }}</span>
                        </label>
                    </div>
                    <!--{% for error in form.keyword.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}-->
                    <div>
                        <label>{{ form.submit(class="btn btn-primary") }}</label>
                    </div>
                </form>
            </div>
        </section>
    </body>
</html>